### ISSUE TITLE
Rating dialog requires iOS 10.3+

### ISSUE THREAD

**Issue by Bhavik-P** [dpa99c/cordova-launch-review#1]
Receiving "Rating dialog requires iOS 10.3+" error when calling the LaunchReview.rating() function on a iOS device running 10.3.1.

**Comment by dpa99c** [comment]
Are you building the app with XCode 8.3?

As well as running on a device with iOS 10.3, the app must be built with XCode 8.3 which includes the new functionality in the iOS 10.3 SDK. 

You can see from [the code](https://github.com/dpa99c/cordova-launch-review/blob/master/src/ios/LaunchReview.m#L52) that iOS 10.3 SDK is required for this functionality to work.

**Comment by Bhavik-P** [comment]
I believe the build was not on XCode 8.3 so I think that may have caused the error. I will build it on a new one and try to see if it fails.
