### ISSUE TITLE
Windows Phone support

### ISSUE THREAD

**Issue by JulianLaval** [dpa99c/cordova-launch-review#10]
Would you be open to supporting Windows Phone in the `launch()` method, which would redirect to the appropriate store URL (e.g. `'ms-windows-store://pdp/?ProductId=<the apps Store ID>'`)?

Happy to submit a PR!

**Comment by dpa99c** [comment]
Since Microsoft has ditched Windows 10 Mobile, as well as Windows Phone, I'm considering both to be deprecated platforms and so will not be making any effort to support them.

However, if you want to implement and test an implementation for those platforms yourself, I'm happy to accept a PR.

**Comment by JulianLaval** [comment]
Thanks for the quick reply.

Definitely not a priority, so I'll investigate whether a PR makes sense for us / would be worth the effort!

**Comment by dpa99c** [comment]
Closing as Windows Phone is obsolete
