### ISSUE TITLE
isRatingSupported() returns true on iPad version 9.3.5

### ISSUE THREAD

**Issue by Deeeej** [dpa99c/cordova-launch-review#11]
Hello,

Great plugin, thanks for all the hard work.

It appears that isRatingSupported() only works correctly on the iPhone, not on the iPad Mini. It returns true in all circumstances on the iPad.

My limited knowledge in this area would suggest this is probably down to the use of the constant: __IPHONE_10_3 AND __IPHONE_OS_VERSION_MAX_ALLOWED in LaunchReview.m.

**Comment by dpa99c** [comment]
You're right on this, it has not been tested on iOS 9 before, so I'll push out a patch release to resolve this issue shortly.

**Comment by dpa99c** [comment]
The fix has been pushed out to npm in v3.1.1

Let me know if you still have an issue.

**Comment by Deeeej** [comment]
Fantastic, thanks very much.
I tested it and it seems to works exactly as expected.
