### ISSUE TITLE
Why "Submit" button is disabled?

### ISSUE THREAD

**Issue by bushev** [dpa99c/cordova-launch-review#14]
![img_0294](https://user-images.githubusercontent.com/7535766/51098440-f28c7700-17fc-11e9-9157-121ed8da1bf5.jpg)

----

**I'm submitting a ...**  (check one with "x"):
- [X] bug report
- [ ] feature request
- [ ] documentation issue

# Bug report

The "Submit" button is disabled. Why?

**Expected behavior:**

The "Submit" button is enabled

**Steps to reproduce:**

Call `this.launchReview.rating()`

**Environment information**

- Cordova CLI version 
	- `8.1.2 (cordova-lib@8.1.1)`
- Cordova platform version
	- `ios 4.5.5`
- Plugins & versions installed in project (including this plugin)
```
com.omarben.inappreview 0.0.5 "inappreview"
cordova-background-geolocation-lt 2.14.2 "BackgroundGeolocation"
cordova-clipboard 1.2.1 "Clipboard"
cordova-fabric-plugin 1.1.14-dev "cordova-fabric-plugin"
cordova-launch-review 3.1.1 "Launch Review"
cordova-plugin-add-swift-support 1.7.2 "AddSwiftSupport"
cordova-plugin-app-version 0.1.9 "AppVersion"
cordova-plugin-background-fetch 5.4.1 "CDVBackgroundFetch"
cordova-plugin-badge 0.8.8 "Badge"
cordova-plugin-cocoalumberjack 0.0.4 "CocoaLumberjack"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-filepicker 1.1.5 "File Picker"
cordova-plugin-fingerprint-aio 1.5.0 "FingerprintAllInOne"
cordova-plugin-google-analytics 1.8.6 "Google Universal Analytics Plugin"
cordova-plugin-httpd 0.9.2 "CorHttpd"
cordova-plugin-ionic-keyboard 2.1.3 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 3.0.0 "cordova-plugin-ionic-webview"
cordova-plugin-local-notification 0.9.0-beta.2 "LocalNotification"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-ssh-tunnel 1.1.0 "SSHTunnel"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-taptic-engine 2.1.0 "Taptic Engine"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-plugin-x-socialsharing 5.4.4 "SocialSharing"
cordova-sqlite-storage 2.6.0 "Cordova sqlite storage plugin"
es6-promise-plugin 4.2.2 "Promise"
```
- Dev machine OS and version, e.g.
```
ProductName:	Mac OS X
ProductVersion:	10.14.2
BuildVersion:	18C54
```

_Runtime issue_
- Device details
    - iPhone XS MAX
- OS details
    -  iOS 12.1.2
	
_iOS build issue:_
- Node JS version
    - `v10.15.0`
- XCode version
   - `10.1`

_If using an [Ionic Native Typescript wrapper]() for this plugin:_
- Ionic environment info
```
Ionic:

   ionic (Ionic CLI)             : 4.7.1 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.0-rc.1
   @angular-devkit/build-angular : 0.11.4
   @angular-devkit/schematics    : 7.1.4
   @angular/cli                  : 7.1.4
   @ionic/angular-toolkit        : 1.2.2

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 3.0.0, (and 22 other plugins)

System:

   Android SDK Tools : 26.1.1 (/Users/bushev/Library/Android/sdk)
   ios-deploy        : 1.9.4
   NodeJS            : v10.15.0 (/usr/local/bin/node)
   npm               : 6.5.0
   OS                : macOS Mojave
   Xcode             : Xcode 10.1 Build version 10B61
```
- Installed Ionic Native modules and versions
```
├─┬ @ionic-native/app-version@5.0.0-beta.23
├─┬ @ionic-native/clipboard@5.0.0-beta.23
├─┬ @ionic-native/core@5.0.0-beta.23
├─┬ @ionic-native/device@5.0.0-beta.23
├─┬ @ionic-native/file@5.0.0-beta.23
├─┬ @ionic-native/fingerprint-aio@5.0.0-beta.23
├─┬ @ionic-native/google-analytics@5.0.0-beta.23
├─┬ @ionic-native/httpd@5.0.0-beta.23
├─┬ @ionic-native/in-app-review@5.0.0-beta.23
├─┬ @ionic-native/launch-review@5.0.0-beta.23
├─┬ @ionic-native/local-notifications@5.0.0-beta.23
├─┬ @ionic-native/social-sharing@5.0.0-beta.23
├─┬ @ionic-native/splash-screen@5.0.0-beta.23
├─┬ @ionic-native/status-bar@5.0.0-beta.23
├─┬ @ionic-native/taptic-engine@5.0.0-beta.23
```

**Comment by bushev** [comment]
Maybe app version should be published?

**Comment by dpa99c** [comment]
The ratings dialog is a native dialog which this plugin invokes but the logic for its display (i.e. whether the Submit button is disabled) lies within iOS itself.

The Submit button will only be enabled in a published app downloaded from the App Store.

**Comment by jesusbm** [comment]
There are two methods to test google's in-app review, 1. internal app sharing and 2. internal test track. 
When you use the first one the submit button is disabled, when you use the second one the submit button is enabled and the user comment is mandatory, for a production release the user comment is optional (and the submit button is enabled, of course).
https://medium.com/googleplaydev/demystifying-the-new-play-in-app-review-api-1a78e351db7a

**Comment by merbin2012** [comment]
Due to this, app reviewer team reject my apps.
