### ISSUE TITLE
The donate button in the github readme is broken.

### ISSUE THREAD

**Issue by ecofriendlyapp** [dpa99c/cordova-launch-review#16]
The donate button in the github readme is broken.
The donation link in FUNDING.yml works but not the one in the readme.

**Comment by dpa99c** [comment]
Thanks for reporting but not sure what's going one cos I just clicked the one in README and it seems to work for me:
![image](https://user-images.githubusercontent.com/2345062/62766915-6c32cd80-ba8b-11e9-8c93-bdbd4051bc3f.png)

Could you try again in incognito or a different browser and confirm there's still an issue?
How was it broken? Did it 404?

**Comment by ecofriendlyapp** [comment]
Here is how it looks when it doesn't work.  (Safari on Mac, accessed from the USA.)  
https://pasteboard.co/Is01t07.png

**Comment by dpa99c** [comment]
Thanks for submitting the PR - so it was the missing `source=url` parameter causing the issue.
I'd better clone your fix to all my other repos!
Thanks again for taking the time to report and fix this!
