### ISSUE TITLE
rating() function returns no other results than "requested"

### ISSUE THREAD

**Issue by rafaellop** [dpa99c/cordova-launch-review#18]
**I'm submitting a ...**  (check one with "x"):
- [x] bug report
- [ ] feature request
- [ ] documentation issue

# Bug report

**Current behavior:**

The  `LaunchReview.rating()` never returns other results than the `requested` result. No `shown` or `dismissed` is ever called.

**Expected behavior:**

The  `LaunchReview.rating()` should work as described in the readme and returns different results for different scenarios.

**Steps to reproduce:**

Call the following code and observe console for the result returned when dealing with the rating window:

```
LaunchReview.rating( function(result) {
  console.log('result:', result);
}, function(err){
 console.log('error:', err);
})
```

**Environment information**

- Cordova CLI version 
8.1.2
- Cordova platform version
4.5.5
- Plugins & versions installed in project (including this plugin)

cordova-launch-review 3.1.1

- Dev machine OS and version, e.g.
    - OSX Mojave 10.14.6
 
XCode 11.3
        
_Runtime issue_
- Device details
iPhone 8 Simulator
- OS details
iOS 13.3
	
- XCode version

XCode 11.3

**Comment by dpa99c** [comment]
Since Rating functionality involves App Store APIs, it does not work on the iOS Simulator and must be tested on a real iOS device which is signed in to the App Store with a real Apple ID

**Comment by julianCast** [comment]
The same is happening to me on a real device, but android, it says successfully opened dialog, but nop, no rating dialog.
Ionic 4
Android 10
