### ISSUE TITLE
Add support for in-app reviews on Android

### ISSUE THREAD

**Issue by terreng** [dpa99c/cordova-launch-review#22]
**I'm submitting a...**
- [ ] bug report
- [x] feature request
- [ ] documentation issue

# Feature request

Add support for the new Google Play In-App Review API to enable in-app review prompts for Android devices. Extend support for the rating() function to work on Android, and update isRatingSupported() to reflect it.

https://developer.android.com/guide/playcore/in-app-review
https://android-developers.googleblog.com/2020/08/in-app-review-api.html

**Comment by rodrigograca31** [comment]
I came here just to see if this plugin had this feature. Looking forward to it!

**Comment by vogloblinsky** [comment]
+1

**Comment by rodrigograca31** [comment]
**Note:** it is being implemented in this "competing" plugin:

https://github.com/pushandplay/cordova-plugin-apprate/pull/281

**Comment by dpa99c** [comment]
Published in version 4.0.0
