### ISSUE TITLE
Android inapp review - optional comment

### ISSUE THREAD

**Issue by didbarbosa** [dpa99c/cordova-launch-review#23]
Hello, first thank you for this great plugin.
On android, we tested internally the new feature (native in app review). It ask for a mandatory comment after giving a rating, but in the documentation screenshots show leaving a comment is optional ?
How to set this plugin to optional ?

Thanks

**Comment by dpa99c** [comment]
The behaviour has changed since the screenshots in the documentation were taken - a comment is now mandatory and there is no API method to make it optional. I guess Google wants to encourage reviews not just ratings.
