### ISSUE TITLE
What for the native code?

### ISSUE THREAD

**Issue by pke** [dpa99c/cordova-launch-review#3]
I wonder why you decided to implement the store calls in native code?
Wouldn't `document.location.href="market://details?id=appId` do the same? Similar for iOS.
The only native function would be the new in-app review. 

I try to understand the historical reason. Maybe this was not possible 2 years ago to just launch the store URLs from script?

**Comment by dpa99c** [comment]
There was a reason. Can't remember that it was :-)
I think I tried just JS to launch it, and it didn't work. Or something.
