### ISSUE TITLE
Launch not working on iOS 11

### ISSUE THREAD

**Issue by Habared** [dpa99c/cordova-launch-review#6]
LaunchReview.launch(storeId) is not working anymore on iOS11.
It launches App Store App but then a message "Cannot Connect to App Store" is displayed.

**Comment by dpa99c** [comment]
It appears that in iOS 11, Apple has disabled the URL format used by this plugin (and may other apps) to open the review section of the App Store page. See https://github.com/nicklockwood/iRate/issues/302

See also https://stackoverflow.com/a/45710637/777265

**Comment by dpa99c** [comment]
Just published v2.0.1 which just opens the App Store page for the app on iOS 11, since it's no longer possible to directly open the review section.

f another mechanism can be found to directly open the Review section on iOS 11, I'll re-open this issue and implement it.

**Comment by GitRubb** [comment]
@dpa99c referring to your latest commit, it actually is possible to directly link to the review page on iOS 11. 

just attach &action=write-review to the the end of the url. This may work for the itms url also I haven't tried yet. 

https://itunes.apple.com/us/app/_app_name_/id_app_id_?mt=8&action=write-review

**Comment by zapjonny** [comment]
That one supposedly breaks as soon as you change app name right?

**Comment by dpa99c** [comment]
Just been doing some empirical testing on iOS 11 and it seems the country code and app name are required in the URL, but not actually used so they can be anything - only the ID needs to be correct for the target app. Also `mt=8` is no longer required, so I've distilled it down to:

    itms-apps://itunes.apple.com/xy/app/foo/id{your_app_id}?action=write-review

where only {your_app_id} needs to change.  

This then works as @GitRubb describes, opening the "Write a Review" popup in the App Store page on iOS 11.

I will push out a patch release to use this URL format on iOS 11+

**Comment by dpa99c** [comment]
Published as `cordova-launch-review@2.0.2`

**Comment by zapjonny** [comment]
> itms-apps://itunes.apple.com/xy/app/foo/id{your_app_id}?action=write-review

<s>Tried it, didn't work on iOS 11.0. Still roots to app store though, but still gets the Can't connect to App Store:ish message. @dpa99c 
</s>

**Comment by zapjonny** [comment]
Update: the itms-apps link works when tapped from Notes on iOS 11.0, but not when opened with `UIApplication.shared.openURL`.

**Comment by dpa99c** [comment]
@zapjonny It works fine when I test it: see [this screencapture](http://ge.tt/5CSxPcm2)

**Comment by zapjonny** [comment]
@dpa99c  Yes sorry I just found out a mistake on my part, I can confirm that the link works. Sorry for the trouble and thanks for this. I guess I will just carry on with this URL for iOS 11.0 for now...
