### ISSUE TITLE
Though i get the msg succesfully launched store app. i get this display

### ISSUE THREAD

**Issue by sankari123** [dpa99c/cordova-launch-review#7]
![screenshot_2017-09-25-13-03-50 1](https://user-images.githubusercontent.com/14199766/30797077-506143ba-a1f2-11e7-8ce9-4bd26f5b0b90.png)

**Comment by dpa99c** [comment]
Check the package name is correct and publicly visible on the Play Store.

You can test using `"com.google.android.apps.maps"` as in the [example project](https://github.com/dpa99c/cordova-launch-review-example/blob/master/www/js/index.js#L4), i.e.

    LaunchReview.launch("com.google.android.apps.maps");

**Comment by dpa99c** [comment]
Closed due to no response from OP
