### ISSUE TITLE
Pass success/error result to rating() "dismissed" event

### ISSUE THREAD

**Issue by JulianLaval** [dpa99c/cordova-launch-review#9]
Thanks for your diligent work on this plugin!

As it stands, the `dismissed` event triggered by the `rating()` method doesn't appear to differentiate between cancellations and successful ratings. I don't suppose it'd be feasible to pass an explicit result?

I haven't yet checked the appropriate HealthKit documentation, but assuming this is feasible I'd be happy to submit a PR.

**Comment by dpa99c** [comment]
The [native method](https://developer.apple.com/documentation/storekit/skstorereviewcontroller/2851536-requestreview) which is [called by this plugin](https://github.com/dpa99c/cordova-launch-review/blob/master/src/ios/LaunchReview.m#L77) does not return any result or outcome so differentiating whether the user has cancelled the dialog or submitted a rating is not possible.

In fact, that native method doesn't even guarantee that the dialog will appear when the method is called, hence this plugin has to use [indirect monitoring of the iOS view hierarchy](https://github.com/dpa99c/cordova-launch-review/blob/master/src/ios/UIWindow%2BDismissNotification.m#L61) to determine when the dialog is shown and dismissed.

**Comment by JulianLaval** [comment]
Fair enough, thanks for the prompt reply!
